name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deps:
    strategy:
      matrix:
        version: ['1.18.0', '1.18.1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: ./.github/actions/setup-go
      with:
        go-version: ${{ matrix.version }}

  test:
    needs: ["deps"]
    strategy:
      matrix:
        version: ['1.18.0', '1.18.1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: ./.github/actions/setup-go
      with:
        go-version: ${{ matrix.version }}
    - name: Test and Bench
      run: go test -v -bench=. ./...

  build:
    needs: ["deps"]
    strategy:
      matrix:
        version: ['1.18.0', '1.18.1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: ./.github/actions/setup-go
      with:
        go-version: ${{ matrix.version }}

    - name: Build and Run
      run: |
        go build
        go run ./main.go
